### ISSUE TITLE
Ios 14.4.2 Home button dismis fix

### ISSUE THREAD

**Issue by erfan1389** [iCrazeiOS/QuickSearch#2]
Hey there, when I swipe up from the buttom of the phone ln the 12 pro max the search bar is still present. Can this be fixed? Thanks a lot.

**Comment by iCrazeiOS** [comment]
you can now tap the home screen to dismiss the search bar, thanks to @Luki120

**Comment by erfan1389** [comment]
Hey there, I still can’t do that. There is no update button either in cydia
or zebra. What should I do? Cheers.

**Comment by iCrazeiOS** [comment]
Do you have the Packix repo added?

On 27 Jan 2022, at 08:52, erfan1389 ***@***.***> wrote:

﻿

Hey there, I still can’t do that. There is no update button either in cydia
or zebra. What should I do? Cheers.

**Comment by erfan1389** [comment]
Hey sorry I just realised it’s because a tweak called “Frame” for live
wallpapers is clashing with it. I disabled it for now. It’s working
perfectly. Thanks for the update I appreciate it :)

**Comment by erfan1389** [comment]
Also a suggestion, would be cool if you could type in urls as well. Right
now if you do that it googles the url rather than opening the url in the
default browser app.
Would make things easjer :) thanks a lot man

**Comment by iCrazeiOS** [comment]
Glad you found the problem

On 27 Jan 2022, at 11:25, erfan1389 ***@***.***> wrote:

﻿

Also a suggestion, would be cool if you could type in urls as well. Right
now if you do that it googles the url rather than opening the url in the
default browser app.
Would make things easjer :) thanks a lot man
